apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mediamanager.fullname" . }}-config
  labels:
    {{- include "mediamanager.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- toToml .Values.mediamanager.config | nindent 4 }}
