replicaCount: 1

image:
  # -- Container image repository for MediaManager.
  repository: ghcr.io/maxdorninger/mediamanager/mediamanager
  # -- MediaManager container image tag. Leave empty to automatically use the Chart's app version.
  tag: ""
  # -- Image pull policy (Always, IfNotPresent, or Never).
  pullPolicy: IfNotPresent

# -- Override the default name of the chart.
nameOverride: ""
# -- Override the default full name of the chart.
fullnameOverride: ""

# -- Annotations to add to the pod.
podAnnotations: {}
# -- Additional labels to add to the pod.
podLabels: {}

# -- Deployment strategy configuration. See `kubectl explain deployment.spec.strategy`.
deploymentStrategy:
  type: RollingUpdate

# -- Liveness probe for the MediaManager container.
livenessProbe:
  httpGet:
    path: /api/v1/health
    port: http

# -- Readiness probe for the MediaManager container.
readinessProbe:
  httpGet:
    path: /api/v1/health
    port: http

# -- Resource requests and limits for the MediaManager container.
resources: {}

persistence:
  images:
    # -- Enable persistence for MediaManager image data. If disabled, image data will be stored in an ephemeral volume.
    enabled: false
    # -- Additional labels to add to the Persistent Volume Claim.
    annotations: {}
    # -- Size of the Persistent Volume Claim for MediaManager image data.
    size: 10Gi
    # -- Storage class for MediaManager image data. Leave empty to use the default StorageClass.
    storageClass: ""
    # -- Access mode for MediaManager image data Persistent Volume Claim.
    accessMode: ReadWriteOnce

service:
  # -- Kubernetes Service type (ClusterIP, NodePort, LoadBalancer, etc.).
  type: ClusterIP
  # -- Additional labels to add to the Service.
  labels: {}
  # -- Annotations to add to the Service.
  annotations: {}
  # -- Port for the MediaManager service.
  port: 8000

# -- Ingress configuration. See: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

mediamanager:
  # -- Port for the MediaManager application.
  port: 8000

  # -- Configuration options for MediaManager. Refer to https://maxdorninger.github.io/MediaManager/configuration.html for possible values.
  config:
    misc: {}

  # -- Environment variables to set in the MediaManager container.
  env: []

  # -- Secret used for token-based authentication.
  # generate a random string with "openssl rand -hex 32", e.g. here https://www.cryptool.org/en/cto/openssl/
  tokenSecret: "CHANGE_ME_GENERATE_RANDOM_STRING"

postgresql:
  # -- enable the Bitnami PostgreSQL chart. Refer to https://github.com/bitnami/charts/blob/main/bitnami/postgresql/ for possible values.
  enabled: false
